name: personal-release
on:
  push:
    tags:
    - v*
env:
  AGE_VERSION: 1.0.0
  GO_VERSION: 1.17.7
  GOFUMPT_VERSION: 0.3.0
  GOLANGCI_LINT_VERSION: 1.44.2
jobs:
  release: # FIXME this should be merged into test-ubuntu above
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get -yq --no-install-suggests --no-install-recommends install musl-tools snapcraft
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
    # The following is needed because chezmoi upgrade and
    # assets/scripts/install.sh have inconsistently looked for
    # chezmoi_${VERSION}_checksums.txt and checksums.txt. To ensure
    # compatibility with all versions, upload checksums.txt as well.
    - name: Upload checksums.txt
      run: |
        VERSION=${GITHUB_REF##*/v}
        cp dist/chezmoi_${VERSION}_checksums.txt dist/checksums.txt
        gh release upload v${VERSION} dist/checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
